---

- name: Install smb server
  ansible.builtin.package:
    name:
      - samba
      - winbind
    state: present
  become: true
  become_user: root

- name: Configure smb
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [wifi-usb]
      browseable = yes
      path = {{ rpi_wifi_usb_smb_share_path }}
      guest ok = yes
      read only = no
      create mask = 777
  notify: Smb reloaded
  become: true
  become_user: root

- name: Enable and start smb
  ansible.builtin.systemd:
    name: smbd.service
    state: started
    enabled: true
  become: true
  become_user: root
